
language: ruby
os: linux
services:
  - docker
before_script:
  - cd ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
script:
  - bundle install
  - bundle exec rake
    cd ..
  - cd java/InterviewQuestions
  - docker build -t javaimg:latest .
  - docker run javaimg
